# Generated by Django 5.2.8 on 2025-12-02 10:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front', models.TextField()),
                ('back', models.TextField()),
                ('stability', models.FloatField(default=4.0)),
                ('difficulty', models.FloatField(default=5.0)),
                ('lapses', models.IntegerField(default=0)),
                ('reps', models.IntegerField(default=0)),
                ('due', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_review', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='decks.deck')),
            ],
        ),
    ]
